# Github Actions Workflow Run Test on example php app

name: Run test suite
on:
  push:
    branches: [ master ]

jobs:
  run-tests:
    name: Run PHPUnit tests
    runs-on: ubuntu-latest
    container:
      image: composer:latest
      volumes:
        - my-app:/app
    steps:
      - name: Running composer install
        run: composer install
      - name: Running phpunit
        run: ./vendor/bin/phpunit tests
